export * from "./baseLayout.js";
export * from "./authTemplates.js";
export * from "./appointmentTemplates.js";
export * from "./ipdTemplates.js";
export * from "./labTemplates.js";
export * from "./billingTemplates.js";
export * from "./pharmacyTemplates.js";
export * from "./insuranceTemplates.js";
export * from "./adminTemplates.js";
