export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  DOCTOR: "DOCTOR",
  NURSE: "NURSE",
  RECEPTIONIST: "RECEPTIONIST",
  ACCOUNTANT: "ACCOUNTANT",
  PHARMACIST: "PHARMACIST",
  PATIENT: "PATIENT",
};

export const SYSTEM_ROLES = Object.values(ROLES);