import { z } from "zod";

export const supplierSchema = z.object({
  name: z.string().trim().min(2, "Supplier name is required"),
  companyType: z.string().optional(),
  gstNumber: z.string().optional(),
  contactPerson: z.string().trim().min(2, "Contact person is required"),
  designation: z.string().optional(),
  phone: z.string().trim().min(5, "Phone number is required"),
  email: z.string().trim().email("Invalid email address").optional().or(z.literal("")),
  alternatePhone: z.string().optional(),
  website: z.string().optional(),
  addressLine1: z.string().optional(),
  addressLine2: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  pinCode: z.string().optional(),
  country: z.string().optional(),
  category: z.string().optional(),
  paymentTerms: z.string().optional(),
  creditLimit: z.union([z.number(), z.string()]).optional(),
  preferredSupplier: z.string().optional(),
  panNumber: z.string().optional(),
  notes: z.string().max(500, "Notes cannot exceed 500 characters").optional(),
  addAnother: z.boolean().optional(),
});
